# Generated by Django 5.1.2 on 2024-10-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('loans', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('key', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('history', models.CharField(max_length=1260)),
                ('borrowed', models.FloatField()),
                ('UserKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSItes.user')),
            ],
        ),
    ]
