# Generated by Django 5.1.2 on 2024-10-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSItes', '0002_remove_usersaccount_history_histroy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
