# Generated by Django 5.1.2 on 2024-10-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSItes', '0003_remove_user_key_remove_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='placeholder',
        ),
    ]
