# Generated by Django 5.1.2 on 2024-10-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSItes', '0004_delete_placeholder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='FRBS',
        ),
        migrations.RemoveField(
            model_name='histroy',
            name='UserKey',
        ),
        migrations.RemoveField(
            model_name='usersaccount',
            name='UserKey',
        ),
        migrations.AddField(
            model_name='bank',
            name='UserKey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainSItes.frbs'),
            preserve_default=False,
        ),
    ]
